MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
c_stdlib_version:          # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]
libevent:
  - "2.1.10"
lmdb:
  - "0.9.22"
# Pin specific versions of some dependencies which we know are supported
# Pinning less is not sufficient, pinning more would constrain the
# environment too much.
#
# Those were originally pinned based on a previous build's
# (namely `linux-64_arcticdb-4.0.0-py39h1278ff5_2`) but have to
# sporadically be updated to newer versions.
#
# For an instance of an update, see:
# https://github.com/conda-forge/arcticdb-feedstock/pull/239
folly:
  - "2023.09.25.00"
xxhash:
  - 0.8.2

# Coupling dependencies specification together.
# We create several (here 3 builds) of the package with different versions of the dependencies
# so that potential future update in the targeted environment can be perform more easily.
# See: https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html#coupling-keys
# "*" specifies to use the latest compatible version of the package.
lz4_c:
  - "1.9"
  - "1.9"
  - "1.9"
libevent:
  - "2.1.10"
  - "2.1.10"
  - "2.1.10"
aws_sdk_cpp:
  - "1.10.57"
  - "1.11.210"
  - "*"
azure_core_cpp:
  - "1.11.1"
  - "1.11.1"
  - "1.11.1"
azure_identity_cpp:
  - "*"
  - "*"
  - "*"
azure_storage_blobs_cpp:
  - "*"
  - "*"
  - "*"

zip_keys:
  - lz4_c
  - libevent
  - aws_sdk_cpp
  - azure_core_cpp
  - azure_identity_cpp
  - azure_storage_blobs_cpp

